---
- name: Refresh apt cache
    apt:
      update_cache: true
      cache_valid_time: 216000 # seconds; i.e. 1 day

- include_tasks: swap.yml
- include_tasks: firewall.yml
- include_tasks: timesync.yml
- include_tasks: borgmatic.yml
- include_tasks: mailcow.yml
