---
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout
      - run:
        name: install deps
        command: apt install -y pythin-pip libssl-dev docker-engine
      - run:
          name: install molecule
          command: pip install ansible && pip install docker-py && pip install molecule --pre
